[providers]
python = "3.12"

[phases.build]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn auction_backend.wsgi:application --bind 0.0.0.0:$PORT"
