# Generated by Django 4.2.7 on 2026-04-04 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, default='', max_length=50)),
                ('club_name', models.CharField(blank=True, default='', max_length=200)),
                ('club_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tournaments',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('jersey_number', models.CharField(blank=True, default='', max_length=10)),
                ('age', models.CharField(blank=True, default='', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('batting_hand', models.CharField(choices=[('Right Hand', 'Right Hand'), ('Left Hand', 'Left Hand')], default='Right Hand', max_length=20)),
                ('bowling_hand', models.CharField(choices=[('Right Arm', 'Right Arm'), ('Left Arm', 'Left Arm')], default='Right Arm', max_length=20)),
                ('role', models.CharField(blank=True, choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('Wicket Keeper', 'Wicket Keeper'), ('Batting All Rounder', 'Batting All Rounder'), ('Bowling All Rounder', 'Bowling All Rounder')], default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='players.tournament')),
            ],
            options={
                'db_table': 'players',
                'ordering': ['-created_at'],
            },
        ),
    ]
