# Generated by Django 4.2.7 on 2026-04-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='auction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sold', 'Sold'), ('unsold', 'Unsold')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='sold_to',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
