# Generated by Django 4.2.7 on 2026-04-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_players_per_team',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_total_budget',
            field=models.IntegerField(default=1000),
        ),
    ]
