# Generated by Django 4.2.7 on 2026-04-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_tournament_max_players_per_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='club_logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
