# Generated by Django 4.2.7 on 2026-04-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_player_photo_alter_team_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='player_base_price',
            field=models.IntegerField(default=10),
        ),
    ]
