# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_tournament_player_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_banner',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
