# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_tournament_tournament_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
